apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: online-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: docker.io/ayaankhan17/frontend:sha-1f708f3d17cc8ac4370242e7cb3af8e4929a62e7
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_PRODUCTS_BASE_URL
              value: "http://3.224.211.19:30081"
            - name: REACT_APP_CUSTOMERS_BASE_URL
              value: "http://3.224.211.19:30082"
            - name: REACT_APP_ORDER_BASE_URL
              value: "http://3.224.211.19:30083"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: online-catalog
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30080
  type: NodePort