name: online-catalog

services:
  catalog-management:
    build:
      context: ./backend/catalog-management
      dockerfile: Dockerfile
    container_name: online-catalog-management
    ports:
      - "8081:8081"
    restart: unless-stopped

  customer-support:
    build:
      context: ./backend/customer-support
      dockerfile: Dockerfile
    container_name: online-customer-support
    environment:
      NODE_ENV: development
      PORT: 8082
      ORDER_PROCESSING_BASE_URL: http://order-processing:8083
    ports:
      - "8082:8082"
    depends_on:
      - order-processing
    restart: unless-stopped

  order-processing:
    build:
      context: ./backend/order-processing
      dockerfile: Dockerfile
    container_name: online-order-processing
    environment:
      NODE_ENV: development
      PORT: 8083
    ports:
      - "8083:8083"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: online-catalog-frontend
    environment:
      REACT_APP_PRODUCTS_BASE_URL: http://localhost:8081
      REACT_APP_CUSTOMERS_BASE_URL: http://localhost:8082
      REACT_APP_ORDER_BASE_URL: http://localhost:8083
    ports:
      - "3000:3000"
    depends_on:
      - catalog-management
      - customer-support
      - order-processing
    restart: unless-stopped
